apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins-master
  template:
    metadata:
      labels:
        name: jenkins-master
    spec:
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins-master
          image: anas1243/jenkins-with-docker
          ports:
            - name: httpport
              containerPort: 8080
          volumeMounts:
            - name: sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: sock
          hostPath:
            path: /var/run/docker.sock
