apiVersion: v1
kind: Service
metadata:
  name: load-balancer-jenkins
spec:
  type: LoadBalancer
  selector:
    name: jenkins-master
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
